// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import SidebarController from "./sidebar_controller.js"
application.register("sidebar", SidebarController)

import TextUpdateController from "./text_update_controller.js"
application.register("text-update", TextUpdateController)

